<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Sucre', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Yotala', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Poroma', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Villa Azurduy', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Tarvita', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'villa zudañez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Presto', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Villa Mojocoya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Icla', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Padilla', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Tomina', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Sopachuy', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Villa Alcalá', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'El Villar', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Monteagudo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'San Pablo de Huacareta', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Tarabuco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Yamparáez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Camargo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'San Lucas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Incahuasi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Villa charcas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Villa Serrano', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Camataqui', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Culpina', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Las Carreras', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Villa Vaca Guzmán', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Huacaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 5, 'mun_nombre'=> 'Macharetí', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'La Paz ', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Palca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Mecapaca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Achocalla', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'El Alto', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Achacachi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Ancoraimes', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Chua Cocani', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Huarina', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Santiago de Huata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Huatajata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Coro Coro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Caquiaviri', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Calacoto', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Comanche', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Charaña', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Waldo Ballivián', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Nazacara de Pacajes', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Santiago de Callapa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Puerto Acosta', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Mocomoco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Puerto Carabuco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Humanata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Escoma', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Chuma ', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Ayata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Aucapata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Sorata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Guanay', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Tacatoma', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Quiabaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Combaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Tipuani', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Mapiri', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Teoponte', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Apolo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Pelechuco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Viacha', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Guaqui', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Tiahuanacu', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Desaguadero', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'San Andrés de Machaca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Jesús de Machaca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Taraco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Luribay', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Sapahaqui', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Yaco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Malla', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Cairoma', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Inquisivi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Quime', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Cajuata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Colquiri', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Ichoca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Licoma Pampa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Chulumani', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Irupana', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Yanacachi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Palos Blancos', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'La Asunta', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Pucarani', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Laja', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Batallas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Puerto Pérez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Sica Sica', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Umala', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Ayo Ayo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Calamarca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Patacamaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Colquencha', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Collana', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Coroico', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Coripata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Ixiamas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'San Buenaventura', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Gral. Juan José Perez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Curva', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Copacabana', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'San Pedro de Tiquina', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Tito Yupanqui', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'San Pedro de Curahuara', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Papel Pampa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Chacarilla', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Santiago de Machaca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Catacora', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Caranavi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 1, 'mun_nombre'=> 'Alto Beni', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Cochabamba', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Aiquile', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Pasorapa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Omereque', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Independencia', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Morochata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Cocapata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Tarata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Anzaldo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Arbieto', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Sacabamba', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Arani', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Vacas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Arque', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Tacopaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Capinota', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Santivañez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Sicaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Cliza', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Toco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Tolata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Quillacollo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Sipe Sipe', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Tiquipaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Vinto', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Colcapirhua', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Sacaba', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Colomi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Villa Tunari', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Tapacarí', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Totora', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Pojo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Pocona', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Chimoré', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Puerto Villaroel', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Entre Ríos', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Mizque', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Vila Vila', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Alalay', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Punata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Villa Rivero', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'San Benito', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Tacachi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Cuchumuela', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Bolivar', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Tiraque', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 4, 'mun_nombre'=> 'Shinahota', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Oruro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Caracollo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'El Choro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Coracachi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Challapata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Santuario de Quillacas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Corque', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Choquecota', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Curahuara de Carangas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Turco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Huachacalla', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Escara', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Cruz de Machacamarca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Yunguyo de Litoral', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Esmeralda', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Villa Poopó', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Pazña', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Antequera', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Villa Huanuni', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Machacamarca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Salinas de Garci Mendoza', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Pampa Aullagas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Sabaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Coipasa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Chipaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Toledo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Eucaliptus', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Andamarca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Belén de Andamarca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Totora', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Santiago de Huari', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'La Rivera', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Todos Santos', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Carangas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 2, 'mun_nombre'=> 'Santiago de Huayllamarca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Potosí', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Tinguipaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Villa de Yocalla', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Belén de Urmiri', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Uncía', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Chayanta', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Llallagua', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Chuquihuta Ayllu Jucumani', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Betanzos', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Chaquí', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Tacobamba', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Colquechaca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Ravelo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Pocoata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Ocurí', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'San Pedro de Buena Vista', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Toro Toro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Cotagaita', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Vitichi', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Sacaca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Caripuyo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Tupiza', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Atocha', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Colcha "K"', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'San Pedro de Quemes', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'San Pablo de Lipez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Mojinete', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'San Antonio de Esmoruco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Puna', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Caiza "D"', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Ckochas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Uyuni', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Tomave', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Porco', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Arampampa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Acasio', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Lica', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Tahua', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'Villazón', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 3, 'mun_nombre'=> 'San Agustin', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Tarija', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Padcaya', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Bermejo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Yacuiba', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Caraparí', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Villamontes', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Uriondo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Yunchará', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'San Lorenzo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'El Puente', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 6, 'mun_nombre'=> 'Entre Ríos', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Santa Cruz de la Sierra', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Cotoca', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Porongo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'La Guardia', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'El Torno', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Warnes', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Okinawa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Ignacio', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Miguel', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Rafael', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Buena Vista', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Carlos', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Yapacaní', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Juan', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San José', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Pailón', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Roboré', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Portachuelo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Santa Rosa del Sara', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Colpa Bélgica', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Lagunillas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Charagua', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Cabezas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Cuevo', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Gutiérrez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Camiri', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Boyuibe', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Vallegrande', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'El Trigal', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Moro Moro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Postrervalle', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Pucará', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Samaipata', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Pampa Grande', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Mairana', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Quirusillas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Montero', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Gral. Saavedra', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Mineros', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Puerto Fernández Alonso', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Pedro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Concepción', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Javier', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Ramón', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Julián', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Antonio de Lomerío', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Cuatro Cañadas', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'San Matías', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Comarapa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Saipana', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Puerto Suárez', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Puerto Quijarro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Carmen Rivero Torres', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Ascención de Guarayos', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'Urubichá', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 9, 'mun_nombre'=> 'El Puente', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Trinidad', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'San Javier', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Riberalta', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Guayaramerín', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Reyes', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'San Borja', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Santa Rosa', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Rurrenabaque', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Santa Ana', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Exaltación', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'San Ignacio', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Loreto', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'San Andrés', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'San Joaquín', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'San Ramón', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Puerto Siles', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Magdalena', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Baures', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 8, 'mun_nombre'=> 'Huacaraje', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Cobija', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Porvenir', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Bolpebra', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Bella Flor', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Puerto Rico', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'San Pedro', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Filadelfia', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Puerto Gonzalo Moreno', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Blanca Flor', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'El Sena', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Santa Rosa de Abuná', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Humaita', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Nueva Esperanza', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Villa Nueva', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('municipio')->insert(['dep_id' => 7, 'mun_nombre'=> 'Santos Mercado', 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
    }
}
