<?php
namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pais')->insert(['pai_nombre' => "BOLIVIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "AFGANISTAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ALBANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ALEMANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ANDORRA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ANGOLA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ANGUILLA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ANTIGUA Y BARBUDA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ANTILLAS HOLANDESAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ARABIA SAUDI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ARGELIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ARGENTINA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ARMENIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ARUBA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "AUSTRALIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "AUSTRIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "AZERBAIYAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BAHAMAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BAHREIN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BANGLADESH", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BARBADOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BELARUS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BELGICA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BELICE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BENIN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BERMUDAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BHUTÁN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BOSNIA Y HERZEGOVINA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BOTSWANA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BRASIL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BRUNEI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BULGARIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BURKINA FASO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "BURUNDI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CABO VERDE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CAMBOYA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CAMERUN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CANADA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CHAD", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CHILE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CHINA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CHIPRE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "COLOMBIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "COMORES", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CONGO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "COREA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "COREA DEL NORTE ", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "COSTA DE MARFIL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "COSTA RICA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CROACIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "CUBA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "DINAMARCA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "DJIBOUTI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "DOMINICA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ECUADOR", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "EGIPTO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "EL SALVADOR", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "EMIRATOS ARABES UNIDOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ERITREA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ESLOVENIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ESPAÑA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ESTADOS UNIDOS DE AMERICA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ESTONIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ETIOPIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "FIJI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "FILIPINAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "FINLANDIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "FRANCIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GABON", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GAMBIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GEORGIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GHANA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GIBRALTAR", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GRANADA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GRECIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GROENLANDIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUADALUPE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUAM", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUATEMALA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUAYANA FRANCESA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUERNESEY", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUINEA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUINEA ECUATORIAL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUINEA-BISSAU", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "GUYANA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "HAITI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "HONDURAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "HONG KONG", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "HUNGRIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "INDIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "INDONESIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "IRAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "IRAQ", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "IRLANDA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLA DE MAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLA NORFOLK", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLANDIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS ALAND", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS CAIMÁN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS COOK", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS DEL CANAL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS FEROE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS MALVINAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS MARIANAS DEL NORTE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS MARSHALL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS PITCAIRN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS SALOMON", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS TURCAS Y CAICOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS VIRGENES BRITANICAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ISRAEL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ITALIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "JAMAICA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "JAPON", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "JERSEY", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "JORDANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "KAZAJSTAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "KENIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "KIRGUISTAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "KIRIBATI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "KUWAIT", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LAOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LESOTHO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LETONIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LIBANO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LIBERIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LIBIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LIECHTENSTEIN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LITUANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "LUXEMBURGO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MACAO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MACEDONIA ", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MADAGASCAR", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MALASIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MALAWI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MALDIVAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MALI", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MALTA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MARRUECOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MARTINICA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MAURICIO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MAURITANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MAYOTTE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MEXICO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MICRONESIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MOLDAVIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MONACO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MONGOLIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MONTENEGRO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MONTSERRAT", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MOZAMBIQUE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "MYANMAR", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NAMIBIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NAURU", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NEPAL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NICARAGUA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NIGER", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NIGERIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NIUE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NORUEGA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NUEVA CALEDONIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "NUEVA ZELANDA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "OMAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PAISES BAJOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PAKISTAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PALAOS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PALESTINA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PANAMA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PAPUA NUEVA GUINEA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PARAGUAY", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PERU", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "POLINESIA FRANCESA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "POLONIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PORTUGAL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "PUERTO RICO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "QATAR", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "REINO UNIDO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "REP.DEMOCRATICA DEL CONGO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "REPUBLICA CENTROAFRICANA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "REPUBLICA CHECA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "REPUBLICA DOMINICANA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "REPUBLICA ESLOVACA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "REUNION", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "RUANDA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "RUMANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "RUSIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAHARA OCCIDENTAL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAMOA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAMOA AMERICANA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAN BARTOLOME", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAN CRISTOBAL Y NIEVES", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAN MARINO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAN MARTIN (PARTE FRANCESA)", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAN PEDRO Y MIQUELON ", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SAN VICENTE Y LAS GRANADINAS", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SANTA HELENA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SANTA LUCIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SANTA SEDE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SANTO TOME Y PRINCIPE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SENEGAL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SERBIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SEYCHELLES", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SIERRA LEONA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SINGAPUR", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SIRIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SOMALIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SRI LANKA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SUDAFRICA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SUDAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SUECIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SUIZA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SURINAM", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SVALBARD Y JAN MAYEN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "SWAZILANDIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TADYIKISTAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TAILANDIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TANZANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TIMOR ORIENTAL", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TOGO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TOKELAU", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TONGA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TRINIDAD Y TOBAGO", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TUNEZ", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TURKMENISTAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TURQUIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "TUVALU", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "UCRANIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "UGANDA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "URUGUAY", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "UZBEKISTAN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "VANUATU", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "VENEZUELA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "VIETNAM", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "WALLIS Y FORTUNA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "YEMEN", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ZAMBIA", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
        DB::table('pais')->insert(['pai_nombre' => "ZIMBABWE", 'created_at'=>date('Y-m-d'), 'updated_at'=>date('Y-m-d')]);
            }
}
